RazorTodoApp/Models/Todo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RazorTodoApp.Models
{
    public class Todo
    {
        [Key]
        public int Id { get; set; }

        public DateTime Date { get; set; } = DateTime.Now;

        [Required]
        [MaxLength(200)]
        public string Task { get; set; }

        [Required]
        [MaxLength(50)]
        public string EstimatedTime { get; set; }

        [Required]
        [MaxLength(50)]
        public string Person { get; set; }

        [MaxLength(50)]
        [Column(TypeName = "varChar(15)")]
        public string Status { get; set; } = "InProgress";
    }
}

RazorTodoApp/Models/TodoDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorTodoApp.Models
{
    public class TodoDbContext : DbContext
    {
        public TodoDbContext(DbContextOptions<TodoDbContext> options) : base(options)
        {

        }

        public DbSet<Todo> Todos { get; set; }
    }
}

RazorTodoApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RazorTodoApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorTodoApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RazorTodoApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

RazorTodoApp/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RazorTodoApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorTodoApp/Pages/TodoList/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorTodoApp.Models;

namespace RazorTodoApp.Pages.TodoList
{
    public class CreateModel : PageModel
    {
        private TodoDbContext _db;

        public CreateModel(TodoDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Todo Todo { get; set; }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                await _db.Todos.AddAsync(Todo);
                await _db.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }
    }
}

RazorTodoApp/Pages/TodoList/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorTodoApp.Models;

namespace RazorTodoApp.Pages.TodoList
{
    public class EditModel : PageModel
    {
        private TodoDbContext _db;

        public EditModel(TodoDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Todo Todo { get; set; }
        public async Task OnGet(int id)
        {
            Todo = await _db.Todos.FindAsync(id);
        }
        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var TodoFromDb = await _db.Todos.FindAsync(Todo.Id);
                TodoFromDb.Date = Todo.Date;
                TodoFromDb.Task = Todo.Task;
                TodoFromDb.EstimatedTime = Todo.EstimatedTime;
                TodoFromDb.Person = Todo.Person;
                TodoFromDb.Status = Todo.Status;

                await _db.SaveChangesAsync();
                return RedirectToPage("Index");
            }
            return RedirectToPage();
        }
    }
}

RazorTodoApp/Pages/TodoList/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorTodoApp.Models;

namespace RazorTodoApp.Pages.TodoList
{
    public class IndexModel : PageModel
    {
        private readonly TodoDbContext _db;

        public IndexModel(TodoDbContext db)
        {
            _db = db;
        }

        public IEnumerable<Todo> Todos { get; set; }

        public async Task OnGet()
        {
            Todos = await _db.Todos.ToListAsync();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            var todo = await _db.Todos.FindAsync(id);
            if (todo == null)
            {
                return NotFound();
            }
            else
            {
                _db.Todos.Remove(todo);
                await _db.SaveChangesAsync();

                return RedirectToPage("Index");
            }
        }
    }
}

RazorTodoApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RazorTodoApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorTodoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorTodoApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/TodoList/Index">Todo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RazorTodoApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

RazorTodoApp/Pages/TodoList/Create.cshtml
@page
@model RazorTodoApp.Pages.TodoList.CreateModel

<br />
<h2 class="text-info">Create New Todo</h2>
<br />

<div class="border container" style="padding:30px">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Todo.Date"></label>
            </div>
            <div class="col-6">
                <input asp-for="Todo.Date" class="form-control" />
            </div>
            <span asp-validation-for="Todo.Date" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Todo.Task"></label>
            </div>
            <div class="col-6">
                <input asp-for="Todo.Task" class="form-control" />
            </div>
            <span asp-validation-for="Todo.Task" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Todo.EstimatedTime"></label>
            </div>
            <div class="col-6">
                <input asp-for="Todo.EstimatedTime" class="form-control" />
            </div>
            <span asp-validation-for="Todo.EstimatedTime" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Todo.Person"></label>
            </div>
            <div class="col-6">
                <input asp-for="Todo.Person" class="form-control" />
            </div>
            <span asp-validation-for="Todo.Person" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Todo.Status"></label>
            </div>
            <div class="col-6">
                <input asp-for="Todo.Status" class="form-control" />
            </div>
            <span asp-validation-for="Todo.Status" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <input type="submit" value="Create" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

}

RazorTodoApp/Pages/TodoList/Edit.cshtml
@page
@model RazorTodoApp.Pages.TodoList.EditModel

<br />
<h2 class="text-info">Create New Todo</h2>
<br />

<div class="border container" style="padding:30px">
    <form method="post">
        <input type="hidden" asp-for="Todo.Id" />
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Todo.Date"></label>
            </div>
            <div class="col-6">
                <input asp-for="Todo.Date" class="form-control" />
            </div>
            <span asp-validation-for="Todo.Date" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Todo.Task"></label>
            </div>
            <div class="col-6">
                <input asp-for="Todo.Task" class="form-control" />
            </div>
            <span asp-validation-for="Todo.Task" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Todo.EstimatedTime"></label>
            </div>
            <div class="col-6">
                <input asp-for="Todo.EstimatedTime" class="form-control" />
            </div>
            <span asp-validation-for="Todo.EstimatedTime" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Todo.Person"></label>
            </div>
            <div class="col-6">
                <input asp-for="Todo.Person" class="form-control" />
            </div>
            <span asp-validation-for="Todo.Person" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Todo.Status"></label>
            </div>
            <div class="col-6">
                <input asp-for="Todo.Status" class="form-control" />
            </div>
            <span asp-validation-for="Todo.Status" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <input type="submit" value="Update" class="btn btn-primary form-control" />
            </div>
            <div class="col-3">
                <a asp-page="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

}

RazorTodoApp/Pages/TodoList/Index.cshtml
@page
@model RazorTodoApp.Pages.TodoList.IndexModel

<br />
<div class="container row p-0 m-0">
    <div class="col-9">
        <h2 class="text-info">Todo List</h2>
    </div>
    <div class="col-3">
        <a asp-page="Create" class="btn btn-info form-control text-white">Create New Todo</a>
    </div>

    <div class="col-12 border p-3 mt-3">
        <form method="post">
            @if (Model.Todos.Count() > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            <label asp-for="Todos.FirstOrDefault().Date"></label>
                        </th>
                        <th>
                            <label asp-for="Todos.FirstOrDefault().Task"></label>
                        </th>
                        <th>
                            <label asp-for="Todos.FirstOrDefault().EstimatedTime"></label>
                        </th>
                        <th>
                            <label asp-for="Todos.FirstOrDefault().Person"></label>
                        </th>
                        <th>
                            <label asp-for="Todos.FirstOrDefault().Status"></label>
                        </th>
                        <th>

                        </th>
                    </tr>
                    @foreach (var item in Model.Todos)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Task)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.EstimatedTime)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Person)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Status)
                            </td>
                            <td>
                                <button asp-page-handler="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to delete?')" class="btn btn-danger btn-sm"> Delete</button>
                                <a asp-page="Edit" asp-route-id="@item.Id" class="btn btn-success btn-sm text-white">Edit</a>
                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>No books available.</p>
            }
        </form>
    </div>
 </div>